server:
  port: 7071
spring:
  application:
    name: feign-client-one
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8091/eureka/,http://slave1:8092/eureka/,http://slave2:8093/eureka/