server:
   port: 8093
spring:
  application:
    name: eureka-server-three #服务名称
eureka:
   instance:
       hostname: slave2
       prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
   client:
       registerWithEureka: true #是否将自己注册到eureka server，构建集群环境时，需将自己注册到集群中，默认为true
       fetchRegistry: true #是否从eureka server获取注册信息，构建集群环境时，需同步其他eureka server节点，默认为true
       serviceUrl:
         defaultZone: http://master:8091/eureka/,http://slave1:8092/eureka/
   #解决eureka server不剔除已停掉的节点问题，更改Eureka更新频率将打破服务器的自我保护功能
   server: 
    enableSelfPreservation: false #设为false，关闭自我保护功能
    evictionIntervalTimerInMs: 4000 #清理间隔（单位毫秒）